packages:
  - renderer
  - packages/*

allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
  msw: false
  "@parcel/watcher": false
  '@depot/cli': true

minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.6'
  - '@better-auth/drizzle-adapter@1.7.6'
  - '@better-auth/kysely-adapter@1.7.6'
  - '@better-auth/memory-adapter@1.7.6'
  - '@better-auth/mongo-adapter@1.7.6'
  - '@better-auth/prisma-adapter@1.7.6'
  - '@better-auth/telemetry@1.7.6'
  - better-auth@1.7.6
  - '@ai-sdk/gateway@4.0.92'
  - '@ai-sdk/mcp@2.0.58'
  - '@ai-sdk/react@4.0.117'
  - ai@7.0.114
  - '@better-auth/cimd@1.7.6'
  - '@better-auth/mcp@1.7.6'
  - '@better-auth/oauth-provider@1.7.6'
