import type { DigiComponentConfig } from "digicomponents"

// French defaults, mirroring what back/src/App.vue passes to DigiComponentConfigProvider.
export const componentConfig: DigiComponentConfig = {
  defaultTexts: {
    backButtonLabel: "Retour",
    cancelCta: "Annuler",
    closeTooltip: "Fermer",
    confirmCta: "Confirmer",
    confirmDeletionModalCta: "Supprimer",
    confirmDeletionModalTitle: "Êtes-vous sûr ?",
    confirmInputIndication: (value) => `Tapez « ${value} » pour confirmer`,
    confirmationPhraseError: "La phrase ne correspond pas",
    copyToClipboardCta: "Copier",
    copiedToClipboard: "Copié !",
    datePlaceholder: "jj/mm/aaaa",
    edit: "Modifier",
    editWysiwyg: "Modifier le texte",
    helpText: "Aide",
    invalidPhoneError: "Numéro de téléphone invalide",
    maxFileSizeError: (maxSize) => `Le fichier dépasse ${maxSize} Mo`,
    okCta: "OK",
    removeFileTooltip: "Supprimer le fichier",
    requiredError: "Ce champ est obligatoire",
    resetCta: "Réinitialiser",
    saveCta: "Enregistrer",
    selectEmptySearch: "Aucun résultat",
    selectedItemsText: "éléments sélectionnés",
    submitCta: "Valider",
    tableEmptyResetCta: "Réinitialiser les filtres",
    tableEmptyText: "Aucun élément",
    timezoneIndicatorContent: (tz) => `Heure exprimée dans le fuseau ${tz}`,
    timeRangeDefaultError: "Plage horaire invalide",
    tableOfContentTitle: "Sommaire",
    selectSuggestionsHeading: "Suggestions",
    dateMinError: (d) => `La date doit être après le ${d}`,
    dateMaxError: (d) => `La date doit être avant le ${d}`,
  },
  extractErrorMessage: (error) => (error instanceof Error ? error.message : "Une erreur est survenue"),
  dateConfig: { locale: "fr", timezone: "Europe/Paris" },
  language: "fr",
}
