// Snapshot JS exports; editable props are validated against the shared manifest.
declare module 'digicomponents' {
  import type { DefineComponent } from 'vue'

  export const DigiAccordion: DefineComponent<Record<string, unknown>>
  export const DigiAccordionCardItem: DefineComponent<Record<string, unknown>>
  export const DigiAccordionContent: DefineComponent<Record<string, unknown>>
  export const DigiAccordionItem: DefineComponent<Record<string, unknown>>
  export const DigiAccordionTrigger: DefineComponent<Record<string, unknown>>
  export const DigiAlert: DefineComponent<Record<string, unknown>>
  export const DigiAvatar: DefineComponent<Record<string, unknown>>
  export const DigiBackButton: DefineComponent<Record<string, unknown>>
  export const DigiBadge: DefineComponent<Record<string, unknown>>
  export const DigiBaseCard: DefineComponent<Record<string, unknown>>
  export const DigiBaseModal: DefineComponent<Record<string, unknown>>
  export const DigiBasicDropdownItem: DefineComponent<Record<string, unknown>>
  export const DigiBasicDropdownMenu: DefineComponent<Record<string, unknown>>
  export const DigiButton: DefineComponent<Record<string, unknown>>
  export const DigiCardCollapsible: DefineComponent<Record<string, unknown>>
  export const DigiCardLayout1: DefineComponent<Record<string, unknown>>
  export const DigiCardListPageLayout: DefineComponent<Record<string, unknown>>
  export const DigiCardTitle: DefineComponent<Record<string, unknown>>
  export const DigiCheckbox: DefineComponent<Record<string, unknown>>
  export const DigiCheckboxFormField: DefineComponent<Record<string, unknown>>
  export const DigiClipboard: DefineComponent<Record<string, unknown>>
  export const DigiCollapsible: DefineComponent<Record<string, unknown>>
  export const DigiCollapsibleContent: DefineComponent<Record<string, unknown>>
  export const DigiCollapsibleTrigger: DefineComponent<Record<string, unknown>>
  export const DigiColorPickerFormField: DefineComponent<Record<string, unknown>>
  export const DigiComponentConfigProvider: DefineComponent<Record<string, unknown>>
  export const DigiConfirmDeletionModal: DefineComponent<Record<string, unknown>>
  export const DigiConfirmInputModal: DefineComponent<Record<string, unknown>>
  export const DigiConfirmModal: DefineComponent<Record<string, unknown>>
  export const DigiCopyIconButton: DefineComponent<Record<string, unknown>>
  export const DigiCustomSearchSelect: DefineComponent<Record<string, unknown>>
  export const DigiDashboardCard: DefineComponent<Record<string, unknown>>
  export const DigiDashboardCardRow: DefineComponent<Record<string, unknown>>
  export const DigiDashboardCardSection: DefineComponent<Record<string, unknown>>
  export const DigiDatePickerFormField: DefineComponent<Record<string, unknown>>
  export const DigiDateTimePickerFormField: DefineComponent<Record<string, unknown>>
  export const DigiDescription: DefineComponent<Record<string, unknown>>
  export const DigiDropdownMenuItem: DefineComponent<Record<string, unknown>>
  export const DigiDropdownMenuLabel: DefineComponent<Record<string, unknown>>
  export const DigiDropdownMenuSeparator: DefineComponent<Record<string, unknown>>
  export const DigiEmailFormField: DefineComponent<Record<string, unknown>>
  export const DigiFileFormField: DefineComponent<Record<string, unknown>>
  export const DigiFileInput: DefineComponent<Record<string, unknown>>
  export const DigiFontSearchSelect: DefineComponent<Record<string, unknown>>
  export const DigiFontSearchSelectFormField: DefineComponent<Record<string, unknown>>
  export const DigiForm: DefineComponent<Record<string, unknown>>
  export const DigiFormCard: DefineComponent<Record<string, unknown>>
  export const DigiFormField: DefineComponent<Record<string, unknown>>
  export const DigiFormFieldContextRenderer: DefineComponent<Record<string, unknown>>
  export const DigiFormModal: DefineComponent<Record<string, unknown>>
  export const DigiFormSheet: DefineComponent<Record<string, unknown>>
  export const DigiGettingStartedChecklist: DefineComponent<Record<string, unknown>>
  export const DigiGroupCard: DefineComponent<Record<string, unknown>>
  export const DigiGroupClickableCard: DefineComponent<Record<string, unknown>>
  export const DigiGroupDraggableCard: DefineComponent<Record<string, unknown>>
  export const DigiIconButton: DefineComponent<Record<string, unknown>>
  export const DigiIconLink: DefineComponent<Record<string, unknown>>
  export const DigiIconRouterLink: DefineComponent<Record<string, unknown>>
  export const DigiIconSidebar: DefineComponent<Record<string, unknown>>
  export const DigiIconSidebarButton: DefineComponent<Record<string, unknown>>
  export const DigiIconSidebarLink: DefineComponent<Record<string, unknown>>
  export const DigiIconSidebarWithPanel: DefineComponent<Record<string, unknown>>
  export const DigiIframe: DefineComponent<Record<string, unknown>>
  export const DigiInformationCard: DefineComponent<Record<string, unknown>>
  export const DigiIntroPageLayout: DefineComponent<Record<string, unknown>>
  export const DigiItemsSelectionPreview: DefineComponent<Record<string, unknown>>
  export const DigiLabel: DefineComponent<Record<string, unknown>>
  export const DigiLink: DefineComponent<Record<string, unknown>>
  export const DigiLinkDropdownItem: DefineComponent<Record<string, unknown>>
  export const DigiMessageModal: DefineComponent<Record<string, unknown>>
  export const DigiModal: DefineComponent<Record<string, unknown>>
  export const DigiModalContent: DefineComponent<Record<string, unknown>>
  export const DigiModalFooter: DefineComponent<Record<string, unknown>>
  export const DigiModalFormField: DefineComponent<Record<string, unknown>>
  export const DigiModalHeader: DefineComponent<Record<string, unknown>>
  export const DigiModalScrollArea: DefineComponent<Record<string, unknown>>
  export const DigiMultiStepModal: DefineComponent<Record<string, unknown>>
  export const DigiMultiStepModalFormStep: DefineComponent<Record<string, unknown>>
  export const DigiMultiStepModalInfoStep: DefineComponent<Record<string, unknown>>
  export const DigiNudeBadge: DefineComponent<Record<string, unknown>>
  export const DigiNudeForm: DefineComponent<Record<string, unknown>>
  export const DigiNudeFormField: DefineComponent<Record<string, unknown>>
  export const DigiNudeModal: DefineComponent<Record<string, unknown>>
  export const DigiNumberFormField: DefineComponent<Record<string, unknown>>
  export const DigiNumberInput: DefineComponent<Record<string, unknown>>
  export const DigiOptionalDateTimePickerFormField: DefineComponent<Record<string, unknown>>
  export const DigiOptionalFormField: DefineComponent<Record<string, unknown>>
  export const DigiOptionalNumberFormField: DefineComponent<Record<string, unknown>>
  export const DigiOptionalSearchSelectFormField: DefineComponent<Record<string, unknown>>
  export const DigiOptionalTextFormField: DefineComponent<Record<string, unknown>>
  export const DigiOverlay: DefineComponent<Record<string, unknown>>
  export const DigiPageHeader: DefineComponent<Record<string, unknown>>
  export const DigiPageTabItem: DefineComponent<Record<string, unknown>>
  export const DigiPagination: DefineComponent<Record<string, unknown>>
  export const DigiPasswordFormField: DefineComponent<Record<string, unknown>>
  export const DigiPhoneFormField: DefineComponent<Record<string, unknown>>
  export const DigiPlaceholderRowCard: DefineComponent<Record<string, unknown>>
  export const DigiPopover: DefineComponent<Record<string, unknown>>
  export const DigiPopoverContent: DefineComponent<Record<string, unknown>>
  export const DigiPopoverTrigger: DefineComponent<Record<string, unknown>>
  export const DigiRadioFormField: DefineComponent<Record<string, unknown>>
  export const DigiRadioGroup: DefineComponent<Record<string, unknown>>
  export const DigiRadioGroupCardItem: DefineComponent<Record<string, unknown>>
  export const DigiRadioGroupFormField: DefineComponent<Record<string, unknown>>
  export const DigiRadioGroupItem: DefineComponent<Record<string, unknown>>
  export const DigiRadioGroupNudeItem: DefineComponent<Record<string, unknown>>
  export const DigiRemixIcon: DefineComponent<Record<string, unknown>>
  export const DigiRemovableChip: DefineComponent<Record<string, unknown>>
  export const DigiRouterLink: DefineComponent<Record<string, unknown>>
  export const DigiRowCard: DefineComponent<Record<string, unknown>>
  export const DigiRowClickableCard: DefineComponent<Record<string, unknown>>
  export const DigiRowDraggableCard: DefineComponent<Record<string, unknown>>
  export const DigiSearchField: DefineComponent<Record<string, unknown>>
  export const DigiSearchSelect: DefineComponent<Record<string, unknown>>
  export const DigiSearchSelectFormField: DefineComponent<Record<string, unknown>>
  export const DigiSettingsCard: DefineComponent<Record<string, unknown>>
  export const DigiSettingsPageLayout: DefineComponent<Record<string, unknown>>
  export const DigiSettingsRowLayout: DefineComponent<Record<string, unknown>>
  export const DigiSheet: DefineComponent<Record<string, unknown>>
  export const DigiSidePanel: DefineComponent<Record<string, unknown>>
  export const DigiSidePanelContent: DefineComponent<Record<string, unknown>>
  export const DigiSidePanelHeader: DefineComponent<Record<string, unknown>>
  export const DigiSingleSettingRow: DefineComponent<Record<string, unknown>>
  export const DigiSortable: DefineComponent<Record<string, unknown>>
  export const DigiSortableElementPicker: DefineComponent<Record<string, unknown>>
  export const DigiSortableHandle: DefineComponent<Record<string, unknown>>
  export const DigiSpinner: DefineComponent<Record<string, unknown>>
  export const DigiStarsRenderer: DefineComponent<Record<string, unknown>>
  export const DigiStepper: DefineComponent<Record<string, unknown>>
  export const DigiSwitch: DefineComponent<Record<string, unknown>>
  export const DigiSwitchFormField: DefineComponent<Record<string, unknown>>
  export const DigiSwitchSingleSettings: DefineComponent<Record<string, unknown>>
  export const DigiTabContent: DefineComponent<Record<string, unknown>>
  export const DigiTable: DefineComponent<Record<string, unknown>>
  export const DigiTableBody: DefineComponent<Record<string, unknown>>
  export const DigiTableCell: DefineComponent<Record<string, unknown>>
  export const DigiTableEmpty: DefineComponent<Record<string, unknown>>
  export const DigiTableEmptyRow: DefineComponent<Record<string, unknown>>
  export const DigiTableFooter: DefineComponent<Record<string, unknown>>
  export const DigiTableHead: DefineComponent<Record<string, unknown>>
  export const DigiTableHeader: DefineComponent<Record<string, unknown>>
  export const DigiTablePageLayout: DefineComponent<Record<string, unknown>>
  export const DigiTableRow: DefineComponent<Record<string, unknown>>
  export const DigiTabsContainer: DefineComponent<Record<string, unknown>>
  export const DigiTabsPageLayout: DefineComponent<Record<string, unknown>>
  export const DigiTextFormField: DefineComponent<Record<string, unknown>>
  export const DigiTextInput: DefineComponent<Record<string, unknown>>
  export const DigiTextPlaceholder: DefineComponent<Record<string, unknown>>
  export const DigiTextPlaceholderWrapper: DefineComponent<Record<string, unknown>>
  export const DigiTextTooltip: DefineComponent<Record<string, unknown>>
  export const DigiTextarea: DefineComponent<Record<string, unknown>>
  export const DigiTextareaFormField: DefineComponent<Record<string, unknown>>
  export const DigiTimePickerFormField: DefineComponent<Record<string, unknown>>
  export const DigiTimeRangePickerFormField: DefineComponent<Record<string, unknown>>
  export const DigiTitle: DefineComponent<Record<string, unknown>>
  export const DigiToast: DefineComponent<Record<string, unknown>>
  export const DigiToggle: DefineComponent<Record<string, unknown>>
  export const DigiToggleGroup: DefineComponent<Record<string, unknown>>
  export const DigiToggleGroupFormField: DefineComponent<Record<string, unknown>>
  export const DigiToggleGroupItem: DefineComponent<Record<string, unknown>>
  export const DigiToggleableFormCard: DefineComponent<Record<string, unknown>>
  export const DigiTooltipIcon: DefineComponent<Record<string, unknown>>
  export const DigiTooltipProvider: DefineComponent<Record<string, unknown>>
  export const DigiTutorialLink: DefineComponent<Record<string, unknown>>
  export const DigiUrlFormField: DefineComponent<Record<string, unknown>>
  export const DigiUrlInput: DefineComponent<Record<string, unknown>>
  export const DigiVerticalMenu: DefineComponent<Record<string, unknown>>
  export const DigiVerticalMenuSub: DefineComponent<Record<string, unknown>>
  export const DigiVerticalMenuSubForm: DefineComponent<Record<string, unknown>>
  export const DigiVerticalMenuTab: DefineComponent<Record<string, unknown>>
  export type DigiComponentConfig = {
    defaultTexts: Record<string, string | ((value: string | number) => string)>
    extractErrorMessage: (error: unknown) => string
    dateConfig: { locale: string; timezone: string }
    language: string
  }
}
